# This is an example of how to run the app in production using secret files and
# using the image from GitHub Packages.

name: docs

services:
    server:
        image: 'ghcr.io/olillin/new-docs:latest'
        restart: unless-stopped
        secrets:
            - database-url
        environment:
            NODE_ENV: production
            DATABASE_URL_FILE: /run/secrets/database-url
        volumes:
            - uploads:/app/uploads
        ports:
            - '3000:3000'
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:18
        restart: always
        user: postgres
        secrets:
            - postgres-password
        volumes:
            - db-data:/var/lib/postgresql
        environment:
            - POSTGRES_DB=docs
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
        expose:
            - 5432
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data:
    uploads:
secrets:
    database-url:
        file: secrets/database-url.txt
    postgres-password:
        file: secrets/postgres-password.txt
